-- Import the ten distinct events advertised by the eight supplied posters.
-- Existing IDs preserve sign-ups; this migration runs once so later admin edits remain intact.
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('bayang-2026-08-04','event','chessynight at Bayang Cafe','A weekly chess meet-up at Bayang Cafe in TTDI.','2026-08-04','2026-08-04T20:30','2026-08-05T00:00','Bayang Cafe, TTDI','https://chessy-night.kishelraj.chatgpt.site/posters/august-lineup.jpg','{"fee":"Free entry; minimum purchase of one drink or meal","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('third-spaces-2026-08-07','event','chessynight × Third Spaces Anniversary','Chess at the Third Spaces anniversary gathering at Localbarat, Ampang.','2026-08-07','2026-08-07T17:00','2026-08-08T00:00','Localbarat, Ampang','https://chessy-night.kishelraj.chatgpt.site/posters/august-lineup.jpg','{"fee":"Free entry; minimum purchase of one drink or meal","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('flint-2026-08-14','event','chessynight × Flint','An evening chess meet-up at Flint Cafe, The Curve.','2026-08-14','2026-08-14T20:30','2026-08-15T00:00','Flint Cafe, The Curve','https://chessy-night.kishelraj.chatgpt.site/posters/flint-august.jpg','{"fee":"Free entry; minimum purchase of one drink or meal","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('coffee-jam-2026-08-28','event','chessynight × The Coffee Jam PJ','A chess meet-up with The Coffee Jam PJ, Young Living and Flydepth, with a DJ set by Choz Island. The individual event poster lists an 8:30pm start.','2026-08-28','2026-08-28T20:30','2026-08-29T00:00','The Coffee Jam PJ','https://chessy-night.kishelraj.chatgpt.site/posters/coffee-jam.jpg','{"fee":"Free entry; minimum purchase of one drink or meal","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('sky-society-2026-09-11','event','chessynight × Sky Society KL','An evening chess meet-up presented by chessynight and Sky Society KL.','2026-09-11','2026-09-11T20:30','2026-09-12T00:00','Sky Society KL, Wisma New Asia','https://chessy-night.kishelraj.chatgpt.site/posters/sky-society.jpg','{"fee":"Free to play; minimum purchase of one drink or meal","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('jaga-cafe-2026-09-26','event','Chess meet-up at Jaga Cafe','An afternoon of chess in collaboration with Jaga Cafe.','2026-09-26','2026-09-26T15:00','2026-09-26T19:00','Jaga Cafe, Taman Botani Perdana, Kuala Lumpur','https://chessy-night.kishelraj.chatgpt.site/posters/jaga-cafe.jpg','{"fee":"Free to play; minimum purchase of one drink","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('subak-2026-10-09','event','chessynight × Subak Restaurant','An evening of over-the-board chess at Subak Restaurant.','2026-10-09','2026-10-09T20:30','2026-10-10T00:00','Subak Restaurant, Kuala Lumpur','https://chessy-night.kishelraj.chatgpt.site/posters/subak.jpg','{"fee":"Free entry; minimum purchase of one drink or meal","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('ladies-chessy-night-vol-2-2026-10-13','event','Ladies chessynight Vol. 2','chessynight × Teman Girls × So-So Hub: beginner lesson, guided and casual play, plus a DJ night with Maira Zamri.','2026-10-10','2026-10-13T20:00','2026-10-14T00:00','So-So Hub, Petaling Jaya','https://chessy-night.kishelraj.chatgpt.site/posters/ladies-night.png','{"fee":"RM20 entry + the cost of your order","format":"Beginner lesson, guided and casual play, DJ night"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('flint-2026-10-23','event','chessynight × Flint','The October chess meet-up with Flint.','2026-10-10','2026-10-23T20:30','2026-10-24T00:00','Flint Cafe, The Curve','https://chessy-night.kishelraj.chatgpt.site/posters/october-lineup.jpg','{"fee":"Free entry; minimum purchase of one drink or meal","format":"Chess meet-up"}','[]','',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
INSERT INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,link,published,updated) VALUES ('halloween-rapid-2026-10-31','event','chessynight × Sideboard — Halloween Rapid Tournament','Halloween Rapid Tournament with Sideboard. The advertised event runs from 3pm to midnight. See the tournament page for registration and playing details.','2026-10-10','2026-10-31T15:00','2026-11-01T00:00','Sideboard','https://chessy-night.kishelraj.chatgpt.site/posters/october-lineup.jpg','{"fee":"Contribution-based entry; minimum purchase of one drink or meal","format":"Rapid tournament"}','[]','https://kishelraj.github.io/Chessynight/?tournament=halloween-rapid-2026-sample',1,1791603225044) ON CONFLICT(id) DO UPDATE SET title=excluded.title,body=excluded.body,event_date=excluded.event_date,end_date=excluded.end_date,venue=excluded.venue,image_url=excluded.image_url,details=excluded.details,link=excluded.link,published=1,updated=excluded.updated;
--> statement-breakpoint
UPDATE tournaments SET start_at=1793430000000,venue='Sideboard',details=json_set(details,'$.fee','Contribution-based entry; minimum purchase of one drink or meal','$.checkIn',NULL,'$.rules','The October poster advertises 31 October, 3pm–midnight, at Sideboard. Exact first-round and check-in times, format and prizes are to be confirmed. The listed Swiss format, rounds and time control remain provisional. Check this page for final playing details.','$.poster','https://chessy-night.kishelraj.chatgpt.site/posters/october-lineup.jpg'),updated=1791603225045 WHERE id='halloween-rapid-2026-sample';
