CREATE TABLE IF NOT EXISTS push_subscriptions (endpoint TEXT PRIMARY KEY, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS push_alerts (id TEXT PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, url TEXT NOT NULL, created INTEGER NOT NULL);
