import {Chess} from '/chess.js';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data={sets:[],posts:[]},list=[],setId=null,postId=null,editIndex=-1;
async function api(path,body){const r=await fetch('/api/admin/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save.');return d}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function notice(id,msg,error=false){$(id).textContent=msg;$(id).className=error?'error':'status-note'}
async function refresh(){try{data=await api('list');renderSaved();notice('loading','')}catch(e){notice('loading',e.message,true)}}
function renderSaved(){$('savedSets').innerHTML=data.sets.length?data.sets.map(s=>'<button class="saved-row" data-set="'+esc(s.id)+'"><b>'+esc(s.title)+'</b><span>'+esc(s.date)+' · '+s.puzzles.length+' puzzles · '+(s.published?(s.date>today()?'Scheduled':'Published'):'Draft')+'</span></button>').join(''):'<p>No custom sets yet. Add your first daily challenge.</p>';$('savedPosts').innerHTML=data.posts.length?data.posts.map(p=>'<button class="saved-row" data-post="'+esc(p.id)+'"><b>'+esc(p.title)+'</b><span>'+esc(p.type)+' · '+esc(p.date)+' · '+(p.published?(p.date>today()?'Scheduled':'Published'):'Draft')+'</span></button>').join(''):'<p>No posts yet.</p>';document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>loadSet(b.dataset.set));document.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>loadPost(b.dataset.post));$('countSets').textContent=data.sets.length;$('countPosts').textContent=data.posts.length}
function newSet(){setId=null;list=[];$('setTitle').value='';$('setDate').value=today();$('setPublished').checked=false;drawList();resetPuzzle();notice('setStatus','New puzzle set.');$('setTitle').focus()}
function loadSet(id){const s=data.sets.find(x=>x.id===id);setId=id;list=structuredClone(s.puzzles);$('setTitle').value=s.title;$('setDate').value=s.date;$('setPublished').checked=Boolean(s.published);drawList();resetPuzzle();notice('setStatus','Editing '+s.title+'. Changing the puzzles starts a fresh leaderboard; attempts already started retain their original puzzles.');$('setEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function drawList(){$('puzzleList').innerHTML=list.length?list.map((p,i)=>'<div class="puzzle-row"><div><b>'+(i+1)+'. '+esc(p.title)+'</b><small>'+esc((Array.isArray(p.solution)?p.solution.join(' '):p.solution))+'</small></div><div class="row-actions"><button type="button" class="secondary" data-edit="'+i+'">Edit</button><button type="button" class="secondary" data-up="'+i+'" '+(i===0?'disabled':'')+' aria-label="Move puzzle '+(i+1)+' up">Up</button><button type="button" class="secondary" data-remove="'+i+'">Remove</button></div></div>').join(''):'<p>Add puzzles below to build this challenge.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editIndex=Number(b.dataset.edit);const p=list[editIndex];$('puzzleTitle').value=p.title;$('fen').value=p.fen;$('solution').value=Array.isArray(p.solution)?p.solution.join(' '):p.solution;$('addPuzzle').textContent='Update puzzle';preview()});document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.up);[list[i-1],list[i]]=[list[i],list[i-1]];resetPuzzle();drawList()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{list.splice(Number(b.dataset.remove),1);resetPuzzle();drawList()});$('puzzleCount').textContent=list.length+' / 100 puzzles'}
function resetPuzzle(){editIndex=-1;$('puzzleTitle').value='';$('fen').value='';$('solution').value='';$('addPuzzle').textContent='Add puzzle';$('positionPreview').innerHTML='<p>Paste a FEN position to preview the board.</p>';notice('puzzleStatus','')}
function preview(){try{const c=new Chess($('fen').value.trim());$('positionPreview').innerHTML=board(c);notice('puzzleStatus',(c.turn()==='w'?'White':'Black')+' to move.')}catch(e){$('positionPreview').innerHTML='<p>Enter a valid FEN position.</p>';notice('puzzleStatus',e.message,true)}}
function validate(p){const c=new Chess(p.fen);if(c.isGameOver())throw Error('This position is already finished.');const line=Array.isArray(p.solution)?p.solution:p.solution.trim().split(/\s+/);if(!line.length||line.length>31||line.length%2!==1)throw Error('Include the player’s move, opponent reply, and continuation. Finish with a player move.');for(const u of line){if(!/^([a-h][1-8]){2}[qrbn]?$/.test(u))throw Error('Use moves such as e2e4, with q/r/b/n for promotion.');c.move({from:u.slice(0,2),to:u.slice(2,4),promotion:u[4]})}return {...p,fen:new Chess(p.fen).fen(),solution:line}}
$('puzzleForm').onsubmit=e=>{e.preventDefault();try{const p=validate({title:$('puzzleTitle').value.trim()||'Find the best move',fen:$('fen').value.trim(),solution:$('solution').value.trim()});if(editIndex>=0)list[editIndex]=p;else{if(list.length>=100)throw Error('Maximum 100 puzzles per set.');list.push(p)}drawList();resetPuzzle();notice('puzzleStatus','Puzzle added. Save the set to keep your changes.')}catch(e){notice('puzzleStatus',e.message,true)}};$('fen').oninput=preview;$('cancelPuzzle').onclick=resetPuzzle;
$('importFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>200000)throw Error('Use a file smaller than 200 KB.');const raw=JSON.parse(await file.text());const puzzles=Array.isArray(raw)?raw:raw.puzzles;if(!Array.isArray(puzzles)||!puzzles.length)throw Error('Use a JSON array of puzzles.');if(list.length+puzzles.length>100)throw Error('Maximum 100 puzzles per set.');const valid=puzzles.map((p,i)=>{try{return validate({title:String(p.title||p.theme||'Find the best move').slice(0,120),fen:p.fen,solution:p.solution})}catch(e){throw Error('Puzzle '+(i+1)+': '+e.message)}});list.push(...valid);drawList();notice('setStatus',valid.length+' puzzles imported. Save the set to keep them.')}catch(e){notice('setStatus',e.message,true)}finally{e.target.value=''}};
$('example').onclick=()=>{const sample=[{title:'Back-rank mate',fen:'6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',solution:['e1e8']}];const blob=new Blob([JSON.stringify(sample,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='chessy-night-puzzle-template.json';a.click();URL.revokeObjectURL(u)};
$('setForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const r=await api('set',{id:setId,title:$('setTitle').value,date:$('setDate').value,published:$('setPublished').checked,puzzles:list});setId=r.id;notice('setStatus',r.message+($('setPublished').checked&&$('setDate').value>today()?' It will appear on its release date in Malaysia.':''));await refresh()}catch(e){notice('setStatus',e.message,true)}finally{btn.disabled=false}};
function postType(){$('eventFields').classList.toggle('hidden',$('postType').value!=='event');$('eventDate').required=$('postType').value==='event'}
function newPost(){postId=null;$('postForm').reset();$('postDate').value=today();postType();notice('postStatus','New post.');$('postTitle').focus()}
function loadPost(id){const p=data.posts.find(x=>x.id===id);postId=id;$('postType').value=p.type;$('postTitle').value=p.title;$('postBody').value=p.body;$('postDate').value=p.date;$('eventDate').value=p.event_date||'';$('venue').value=p.venue||'';$('postLink').value=p.link||'';$('postPublished').checked=Boolean(p.published);postType();notice('postStatus','Editing '+p.title);$('postEditor').scrollIntoView({behavior:'smooth',block:'start'})}
$('postForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const r=await api('post',{id:postId,type:$('postType').value,title:$('postTitle').value,body:$('postBody').value,date:$('postDate').value,eventDate:$('eventDate').value,venue:$('venue').value,link:$('postLink').value,published:$('postPublished').checked});postId=r.id;notice('postStatus',r.message);await refresh()}catch(e){notice('postStatus',e.message,true)}finally{btn.disabled=false}};$('postType').onchange=postType;$('newSet').onclick=newSet;$('newPost').onclick=newPost;
$('tabPuzzles').onclick=()=>{ $('puzzleArea').classList.remove('hidden');$('postArea').classList.add('hidden');$('tabPuzzles').classList.add('primary');$('tabPosts').classList.remove('primary')};$('tabPosts').onclick=()=>{$('postArea').classList.remove('hidden');$('puzzleArea').classList.add('hidden');$('tabPosts').classList.add('primary');$('tabPuzzles').classList.remove('primary')};
$('setDate').value=today();$('postDate').value=today();postType();drawList();refresh();
