import {Chess} from 'chess.js';
import {puzzles as originals} from './puzzles.js';
import {woodpeckerPuzzles} from './woodpecker.js';
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const db=env=>{if(!env.DB)throw Error('Storage unavailable');return env.DB};
export const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
export const isAdmin=req=>Boolean(req.headers.get('oai-authenticated-user-id'))&&req.headers.get('oai-authenticated-user-email')?.toLowerCase()==='kishelraj@gmail.com';
export const rolePermissions={owner:['puzzles','events','photos','registrations','users'],editor:['puzzles','events','photos','registrations'],events:['events','photos','registrations'],puzzles:['puzzles'],viewer:[]};
export const adminIdentity=req=>({email:(req.headers.get('oai-authenticated-user-email')||'').trim().toLowerCase(),accountUserId:req.headers.get('oai-authenticated-user-id')||null});
export async function adminRole(req,env){const identity=adminIdentity(req);if(!identity.accountUserId||!identity.email)return null;if(identity.email==='kishelraj@gmail.com')return 'owner';const row=await db(env).prepare('SELECT role FROM admin_users WHERE email=? AND enabled=1').bind(identity.email).first();return row&&rolePermissions[row.role]?row.role:null}
export function validDate(d){return typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d+'T00:00:00Z'))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d}
export function lineMove(c,uci){if(typeof uci!=='string'||!/^([a-h][1-8]){2}[qrbn]?$/.test(uci))throw Error('Use coordinate moves such as e2e4 or a7a8q.');return c.move({from:uci.slice(0,2),to:uci.slice(2,4),promotion:uci[4]})}
export function validatePuzzles(list){if(!Array.isArray(list)||list.length<1||list.length>100)throw Error('Add between 1 and 100 puzzles.');return list.map((p,i)=>{try{const c=new Chess(p.fen);if(c.isGameOver())throw Error('The position is already finished.');const solution=typeof p.solution==='string'?p.solution.trim().split(/\s+/):p.solution;if(!Array.isArray(solution)||!solution.length||solution.length>31||solution.length%2!==1)throw Error('A solution must start and finish with the player’s move.');for(const m of solution)lineMove(c,m);return {fen:new Chess(p.fen).fen(),title:String(p.title||p.theme||'Find the best move').slice(0,120),solution}}catch(e){throw Error('Puzzle '+(i+1)+': '+e.message)}})}
export function classic(){return {id:'classic',title:'CHESSYNIGHT Start Set',date:'',puzzles:originals.map(p=>{const c=new Chess(p.fen);for(const m of c.moves({verbose:true})){c.move(m);const mate=c.isCheckmate();c.undo();if(mate)return {...p,title:p.theme,solution:[m.from+m.to+(m.promotion||'')],mate:true}}})}}
export async function currentSet(env,id){const row=id&&id!=='classic'?await db(env).prepare('SELECT * FROM challenge_sets WHERE id=? AND published=1 AND date<=?').bind(id,today()).first():id==='classic'?null:await db(env).prepare('SELECT * FROM challenge_sets WHERE published=1 AND date<=? ORDER BY date DESC,updated DESC LIMIT 1').bind(today()).first();if(id&&id!=='classic'&&!row)return null;return row?{...row,puzzles:JSON.parse(row.puzzles)}:classic()}
export async function adminAPI(req,env,path){await seedClubEvent(env);const role=await adminRole(req,env);if(!role)return json({error:'You do not have admin access.'},403);if(req.method==='GET'){if(path==='/api/admin/registrations'){if(!rolePermissions[role].includes('registrations'))return json({error:'Your role cannot view registrations.'},403);const eventId=new URL(req.url).searchParams.get('event');return json({rows:(await db(env).prepare('SELECT name,email,created FROM registrations WHERE event_id=? ORDER BY created DESC').bind(eventId||'').all()).results})}if(path==='/api/admin/users'){if(role!=='owner')return json({error:'Only the owner can manage access.'},403);return json({users:(await db(env).prepare('SELECT id,email,account_user_id,username,role,enabled,created,updated FROM admin_users ORDER BY created ASC').all()).results})}return json({role,permissions:rolePermissions[role],sets:(await db(env).prepare('SELECT * FROM challenge_sets ORDER BY date DESC,updated DESC').all()).results.map(s=>({...s,puzzles:JSON.parse(s.puzzles)})),posts:(await db(env).prepare('SELECT * FROM posts ORDER BY date DESC,updated DESC').all()).results})}
if(req.method!=='POST')return json({error:'Method not allowed.'},405);const b=await req.json();if(path==='/api/admin/user'){if(role!=='owner')return json({error:'Only the owner can manage access.'},403);const email=typeof b.email==='string'?b.email.trim().toLowerCase():'';const username=typeof b.username==='string'?b.username.trim():'';const userRole=typeof b.role==='string'?b.role:'';if(!/^\S+@[^\s@]+\.[^\s@]+$/.test(email)||username.length<2||username.length>80||!Object.hasOwn(rolePermissions,userRole))return json({error:'Enter a valid email, name, and access level.'},400);const now=Date.now();await db(env).prepare('INSERT INTO admin_users (id,email,account_user_id,username,role,enabled,created,updated) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET username=excluded.username,role=excluded.role,enabled=excluded.enabled,updated=excluded.updated').bind(crypto.randomUUID(),email,null,username,userRole,1,now,now).run();return json({message:'Access updated.'})}if(path==='/api/admin/photo'){if(!rolePermissions[role].includes('photos'))return json({error:'Your role cannot edit photos.'},403);return await uploadPhoto(b,env)}if(!validDate(b.date))return json({error:'Choose a valid release date.'},400);const title=typeof b.title==='string'?b.title.trim():'';if(!title||title.length>120)return json({error:'Enter a title of 1–120 characters.'},400);const id=typeof b.id==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(b.id)?b.id:crypto.randomUUID();
if(path==='/api/admin/set'){if(!rolePermissions[role].includes('puzzles'))return json({error:'Your role cannot edit puzzle sets.'},403);let list;try{list=validatePuzzles(b.puzzles)}catch(e){return json({error:e.message},400)}await db(env).prepare('INSERT INTO challenge_sets (id,title,date,published,puzzles,updated) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,date=excluded.date,published=excluded.published,puzzles=excluded.puzzles,updated=excluded.updated').bind(id,title,b.date,b.published?1:0,JSON.stringify(list),Date.now()).run();return json({id,message:b.published?'Puzzle set published.':'Draft saved.'})}
if(path==='/api/admin/post'){if(!rolePermissions[role].includes('events'))return json({error:'Your role cannot edit events or announcements.'},403);if(!['news','event','announcement'].includes(b.type)||typeof b.body!=='string'||!b.body.trim()||b.body.length>10000)return json({error:'Choose a content type and enter up to 10,000 characters.'},400);if(b.type==='event'&&(!validDate(b.eventDate?.slice(0,10))||!/^\d{4}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d$/.test(b.eventDate)))return json({error:'Choose an event date and time.'},400);let imageUrl=typeof b.imageUrl==='string'?b.imageUrl.trim():'';if(imageUrl&&imageUrl!=='/club-poster.webp'){try{const u=new URL(imageUrl);if(u.protocol!=='https:')throw Error()}catch{return json({error:'Use an https:// image URL.'},400)}}let endDate=b.endDate||null;if(endDate&&(!validDate(endDate.slice(0,10))||!/^\d{4}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d$/.test(endDate)||endDate<=b.eventDate))return json({error:'End time must be after the event start.'},400);let link=b.link?.trim()||'';if(link){try{const u=new URL(link);if(u.protocol!=='https:')throw Error()}catch{return json({error:'Use a full https:// link.'},400)}}const details={};for(const key of ['fee','format','levels','equipment','arrival','map']){const v=b.details?.[key];if(v!==undefined&&typeof v!=='string')return json({error:'Invalid event information.'},400);details[key]=String(v||'').trim().slice(0,key==='map'?1000:300)}if(details.map&&!safeImageURL(details.map))return json({error:'Use an HTTPS map link.'},400);const photos=b.photos||[];if(!Array.isArray(photos)||photos.length>8||photos.some(p=>!p||!safeImageURL(p.url)||typeof p.caption!=='string'||p.caption.length>200))return json({error:'Add up to eight photos with valid image links and short captions.'},400);await db(env).prepare('INSERT INTO posts (id,type,title,body,date,event_date,venue,link,image_url,end_date,details,photos,published,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET type=excluded.type,title=excluded.title,body=excluded.body,date=excluded.date,event_date=excluded.event_date,venue=excluded.venue,link=excluded.link,image_url=excluded.image_url,end_date=excluded.end_date,details=excluded.details,photos=excluded.photos,published=excluded.published,updated=excluded.updated').bind(id,b.type,title,b.body.trim(),b.date,b.type==='event'?b.eventDate:null,String(b.venue||'').slice(0,200),link,imageUrl||null,b.type==='event'?endDate:null,JSON.stringify(details),JSON.stringify(photos),b.published?1:0,Date.now()).run();return json({id,message:b.published?'Post published.':'Draft saved.'})}return json({error:'Not found'},404)}
export async function rankingKey(set){if(set.id==='classic')return 'classic';const canonical=JSON.stringify(set.puzzles.map(p=>({fen:p.fen,solution:p.solution})));const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));return set.id+':'+Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}

// Initial event is grounded in the club's supplied 9 October meetup poster.
// INSERT OR IGNORE keeps later admin edits and unpublishing authoritative.
export async function registerEvent(req,env){const b=await req.json();const name=typeof b.name==='string'?b.name.trim():'';const email=typeof b.email==='string'?b.email.trim().toLowerCase():'';if(name.length<2||name.length>80||/[\u0000-\u001f]/.test(name)||email.length>254||!/^\S+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:'Enter your name and a valid email address.'},400);if(b.consent!==true)return json({error:'Please agree to share your details with the event organiser.'},400);const event=await db(env).prepare("SELECT * FROM posts WHERE id=? AND type='event' AND published=1 AND date<=?").bind(b.eventId||'',today()).first();if(!event)return json({error:'This event is not available.'},404);const closes=event.end_date?new Date(event.end_date+'+08:00').getTime():new Date(event.event_date.slice(0,10)+'T23:59:59+08:00').getTime();if(Date.now()>=closes)return json({error:'Sign-ups for this event have closed.'},409);if(event.link)return json({error:'Please use the event registration link.'},409);await db(env).prepare('INSERT OR IGNORE INTO registrations (id,event_id,name,email,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),event.id,name,email,Date.now()).run();return json({message:'Your sign-up is saved. See you at '+event.venue+'!',title:event.title})}

export function safeImageURL(value){if(typeof value!=='string'||value.length>2000)return false;if(/^\/media\/[a-f0-9-]{36}\.webp$/.test(value))return true;try{return new URL(value).protocol==='https:'}catch{return false}}
export async function seedClubEvent(env){const now=Date.now();await db(env).prepare('INSERT OR IGNORE INTO admin_users (id,email,account_user_id,username,role,enabled,created,updated) VALUES (?,?,?,?,?,?,?,?)').bind('owner-kishelraj','kishelraj@gmail.com',null,'kishelraj','owner',1,now,now).run();const insert='INSERT OR IGNORE INTO posts (id,type,title,body,date,event_date,end_date,venue,image_url,details,photos,published,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)';await db(env).prepare(insert).bind('subak-2026-10-09','event','Chess meet-up at Subak','Join CHESSYNIGHT for an evening of over-the-board chess at Subak Restaurant, Kuala Lumpur. The meetup runs from 8:30 PM to midnight.','2026-10-09','2026-10-09T20:30','2026-10-10T00:00','Subak Restaurant, Kuala Lumpur','/club-poster.webp','{}','[]',1,now).run();await db(env).prepare(insert).bind('jaga-cafe-2026-09-26','event','Chess meet-up at Jaga Cafe','An afternoon of chess at Jaga Cafe, in collaboration with CHESSYNIGHT. Free to play, with a minimum purchase of one drink from the cafe.','2026-09-26','2026-09-26T15:00','2026-09-26T19:00','Jaga Cafe, Taman Botani Perdana, Kuala Lumpur','https://kishelraj.github.io/Chessynight/events/jaga-cafe.jpg',JSON.stringify({fee:'Free to play; minimum one drink purchase',format:'Casual chess meet-up'}),'[]',1,now).run();await db(env).prepare(insert).bind('ladies-chessy-night-vol-2-2026-10-13','event','Ladies CHESSYNIGHT Vol. 2','A ladies-only CHESSYNIGHT with beginner lessons, guided games, casual play, and a DJ night with Maira Zamri. Entry is RM20 plus one drink of your choice.','2026-10-09','2026-10-13T20:00','2026-10-14T00:00','So-So Hub, Petaling Jaya','/ladies-chessy-vol-2.png',JSON.stringify({fee:'RM20 entry + one drink (your order)',format:'Beginner lesson · Guided + Casual Play · DJ Night',levels:'Ladies-only event; beginner-friendly and open to casual players',equipment:'Boards and pieces provided; bring your own set if preferred',arrival:'So-So Hub, Petaling Jaya. Details will be confirmed by the organisers.'}),'[]',1,now).run();await db(env).prepare('INSERT OR IGNORE INTO challenge_sets (id,title,date,published,puzzles,updated) VALUES (?,?,?,?,?,?)').bind('woodpecker-puzzles','Advanced',today(),1,JSON.stringify(woodpeckerPuzzles),now).run()}
async function uploadPhoto(b,env){if(!env.PHOTOS)return json({error:'Photo storage is temporarily unavailable.'},503);if(typeof b.data!=='string'||b.data.length>5600000)return json({error:'Use a photo smaller than 4 MB.'},413);let bytes;try{bytes=Uint8Array.from(atob(b.data),c=>c.charCodeAt(0))}catch{return json({error:'Invalid photo file.'},400)}if(bytes.length<16||bytes.length>4000000||String.fromCharCode(...bytes.slice(0,4))!=='RIFF'||String.fromCharCode(...bytes.slice(8,12))!=='WEBP')return json({error:'Upload a valid WebP photo.'},400);const key=crypto.randomUUID()+'.webp';await env.PHOTOS.put(key,bytes,{httpMetadata:{contentType:'image/webp'}});return json({url:'/media/'+key})}
