let lessonId=null,lessonAdminData={lessons:[],canEdit:false,canCheckIn:false};
const localLessonTime=v=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)).replace(' ','T'):'';
const lessonInput=(id,label,type='text',required=false,max='')=>'<div><label for="l-'+id+'">'+label+'</label><input id="l-'+id+'" name="'+id+'" type="'+type+'" '+(required?'required ':'')+(max?'maxlength="'+max+'"':'')+'></div>';
const lessonArea=document.createElement('section');lessonArea.id='lessonArea';lessonArea.className='admin-layout hidden';
lessonArea.innerHTML='<aside class="panel saved"><div class="section-head"><h2>Lessons</h2><button class="secondary" id="newLesson">New lesson</button></div><div id="savedLessons" role="status"></div></aside><div><section class="panel" id="lessonEditor"><h2>Adult lesson editor</h2><p>Individual sessions for adults aged 18+. All times are Malaysia time.</p><form id="lessonForm"><fieldset id="lessonFields" style="border:0;padding:0;margin:0;min-width:0"><div class="tournament-admin-fields">'+lessonInput('title','Class topic','text',true,120)+lessonInput('venue','Location & address','text',true,200)+lessonInput('start','Class date & time','datetime-local',true)+lessonInput('fee','Price (e.g. RM 50 or Free)','text',true,120)+lessonInput('capacity','Maximum students','number',true)+lessonInput('duration','Duration (minutes)','number',true)+lessonInput('teacher','Teacher name','text',true,120)+lessonInput('teacherPhoto','Teacher photo URL (optional)','text',false,2000)+lessonInput('map','Venue map link','url',false,2000)+'<div><label for="l-level">Class level</label><select id="l-level"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div><div class="wide"><label for="l-teacherBio">Teacher introduction</label><textarea id="l-teacherBio" maxlength="1500"></textarea><label for="l-teacherUpload">Upload teacher photo</label><input id="l-teacherUpload" type="file" accept="image/jpeg,image/png,image/webp"><p id="lessonPhotoStatus" role="status"></p><label for="l-outcomes">What students will learn</label><textarea id="l-outcomes" required maxlength="2000"></textarea><label for="l-outline">Lesson outline</label><textarea id="l-outline" maxlength="3000"></textarea><label for="l-prerequisites">Prerequisites</label><textarea id="l-prerequisites" maxlength="1000"></textarea><label for="l-bring">What to bring</label><textarea id="l-bring" maxlength="1000"></textarea></div></div><label class="check"><input id="l-provisional" type="checkbox"> Sample lesson / provisional details</label><label class="check"><input id="l-published" type="checkbox"> Publish lesson</label><label class="check"><input id="l-open" type="checkbox"> Accept bookings until class starts or capacity is reached</label><button class="primary" type="submit">Save lesson</button></fieldset><p id="lessonSaveStatus" role="status"></p></form></section><section class="panel" style="margin-top:24px"><div class="section-head"><h2>Students & attendance</h2><button id="refreshLessonEntries" class="secondary">Refresh students</button></div><div id="lessonEntries" role="status">Save or select a lesson to view its students.</div></section></div>';
$('admin-main').append(lessonArea);
const lessonTab=document.createElement('button');lessonTab.id='tabLessons';lessonTab.className='secondary';lessonTab.textContent='Lessons';$('tabPosts').after(lessonTab);
for(const id of ['tabPuzzles','tabPosts','tabTournaments'])$(id).addEventListener('click',()=>{lessonArea.classList.add('hidden');lessonTab.classList.remove('primary')});
lessonTab.onclick=()=>{for(const id of ['puzzleArea','postArea','tournamentArea'])$(id).classList.add('hidden');for(const id of ['tabPuzzles','tabPosts','tabTournaments'])$(id).classList.remove('primary');lessonArea.classList.remove('hidden');lessonTab.classList.add('primary');loadLessons()};
$('l-capacity').min='1';$('l-capacity').max='1000';$('l-duration').min='15';$('l-duration').max='480';
async function loadLessons(){
  $('savedLessons').textContent='Loading…';
  try{lessonAdminData=await api('lessons');$('lessonFields').disabled=!lessonAdminData.canEdit;$('newLesson').disabled=!lessonAdminData.canEdit;
    $('savedLessons').innerHTML=lessonAdminData.lessons.length?lessonAdminData.lessons.map(t=>'<button class="saved-row" data-edit-lesson="'+esc(t.id)+'"><b>'+esc(t.title)+'</b><span>'+esc(localLessonTime(t.start_at).replace('T',' '))+' MYT · '+(t.published?'Published':'Draft')+'</span><span>'+t.registered+' / '+t.capacity+' students</span></button>').join(''):'<p>No lessons yet. Create a draft to get started.</p>';
    document.querySelectorAll('[data-edit-lesson]').forEach(b=>b.onclick=()=>editLesson(b.dataset.editLesson));
    if(!lessonAdminData.canEdit)notice('lessonSaveStatus','Your role has read-only access to lesson details.');
  }catch(e){$('savedLessons').textContent=e.message}
}
function newLesson(){lessonId=null;$('lessonForm').reset();$('lessonEntries').textContent='Save this lesson to manage registrations.';notice('lessonSaveStatus','New draft.');$('l-title').focus()}
function editLesson(id){const t=lessonAdminData.lessons.find(t=>t.id===id);if(!t)return;lessonId=id;for(const k of ['title','venue','capacity'])$('l-'+k).value=t[k];$('l-start').value=localLessonTime(t.start_at);for(const k of ['fee','teacher','teacherBio','teacherPhoto','level','duration','map','outcomes','outline','prerequisites','bring'])$('l-'+k).value=t.details[k]||'';$('l-provisional').checked=Boolean(t.details.provisional);$('l-published').checked=Boolean(t.published);$('l-open').checked=Boolean(t.registration_open);notice('lessonSaveStatus','Editing '+t.title);loadLessonEntries();$('lessonEditor').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadLessonEntries(){
  const el=$('lessonEntries');if(!lessonId){el.textContent='Save or select a lesson first.';return}if(!lessonAdminData.canCheckIn){el.textContent='Your role does not have access to player contact details or attendance.';return}
  el.textContent='Loading students…';const selectedId=lessonId;
  try{const d=await api('lesson-entries?id='+encodeURIComponent(selectedId));if(selectedId!==lessonId)return;
    el.innerHTML='<p class="tournament-admin-counts">'+d.entries.length+' booked · '+d.entries.filter(e=>e.checked_in).length+' present</p>'+(d.entries.length?'<div class="tournament-table-wrap"><table><thead><tr><th>Student</th><th>Contact</th><th>Experience</th><th>Check-in</th></tr></thead><tbody>'+d.entries.map(e=>'<tr><td>'+esc(e.name)+'</td><td>'+esc(e.email)+(e.phone?'<small>'+esc(e.phone)+'</small>':'')+'</td><td>'+(esc(e.experience)??'Not provided')+'</td><td><button class="secondary" data-checkin="'+esc(e.id)+'" data-checked="'+Boolean(e.checked_in)+'">'+(e.checked_in?'Undo attendance':'Mark present')+'</button></td></tr>').join('')+'</tbody></table></div>':'<p>No students booked yet.</p>');
    el.querySelectorAll('[data-checkin]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('lesson-checkin',{id:button.dataset.checkin,lessonId:selectedId,checkedIn:button.dataset.checked!=='true'});await loadLessonEntries()}catch(e){notice('lessonSaveStatus',e.message,true);button.disabled=false}});
  }catch(e){el.textContent=e.message}
}
$('newLesson').onclick=newLesson;$('refreshLessonEntries').onclick=loadLessonEntries;
$('lessonForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const result=await api('lesson',{id:lessonId,title:$('l-title').value,venue:$('l-venue').value,start:$('l-start').value,capacity:$('l-capacity').value,published:$('l-published').checked,registrationOpen:$('l-open').checked,details:{provisional:$('l-provisional').checked,...Object.fromEntries(['fee','teacher','teacherBio','teacherPhoto','level','duration','map','outcomes','outline','prerequisites','bring'].map(k=>[k,$('l-'+k).value]))}});lessonId=result.id;notice('lessonSaveStatus',result.message);await loadLessons();await loadLessonEntries()}catch(err){notice('lessonSaveStatus',err.message,true)}finally{button.disabled=false}};

$('l-teacherUpload').onchange=async e=>{const file=e.target.files[0];if(!file)return;const controls=[$('lessonFields'),$('newLesson'),$('tabLessons'),...document.querySelectorAll('[data-edit-lesson]')],states=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15000000)throw Error('Use JPEG, PNG or WebP smaller than 15 MB.');notice('lessonPhotoStatus','Uploading…');const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const result=await api('photo',{data:canvas.toDataURL('image/webp',.86).split(',')[1]});$('l-teacherPhoto').value=result.url;notice('lessonPhotoStatus','Photo uploaded. Save the lesson to publish it.')}catch(err){notice('lessonPhotoStatus',err.message,true)}finally{controls.forEach((c,i)=>c.disabled=states[i]);e.target.value=''}};
