const lessonEnquiry='https://wa.me/60172188005?text='+encodeURIComponent('Hi chessynight! I am interested in chess lessons for adults. Please tell me about upcoming classes.');
let lessonView=0;
function lessonFacts(t){const d=t.details;return '<dl class="tournament-facts">'+[['Location',t.venue],['Teacher',d.teacher],['Level',d.level],['Duration',d.duration+' minutes'],['Price',d.fee],['Class size',t.capacity+' adults']].map(([k,v])=>'<div><dt>'+k+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl>'}
function lessonImage(url,label,portrait=false){return url?'<img class="lesson-image" src="'+esc(tournamentPhotoURL(url))+'" alt="'+esc(label)+'" loading="lazy">':'<div class="lesson-image-placeholder'+(portrait?' portrait':'')+'" role="img" aria-label="'+esc(label)+'"><span class="eyebrow"><span class="brand-name">chessynight</span></span><strong>'+esc(portrait?'Teacher photo':'Class photo')+'</strong><span>Coming soon</span></div>'}
function lessonTeacher(t){const d=t.details;return '<article class="panel lesson-teacher">'+lessonImage(d.teacherPhoto,d.teacher+' — photo',true)+'<div><p class="eyebrow">'+esc(d.level)+' classes</p><h3>'+esc(d.teacher)+'</h3>'+(d.teacherBio?'<p>'+esc(d.teacherBio)+'</p>':'')+'</div></article>'}
async function lessonsPage(){
  if(!leave())return;clearInterval(timer);clearInterval(eventTimer);activeNav('lessonsNav');document.title='chessynight — Chess lessons for adults';app.className='lessons-page';
  app.innerHTML='<div class="eyebrow">Chess lessons · Adults 18+</div><h1>Learn the game.<br>Find your people.</h1><p class="lesson-intro">Small-group chess lessons for adults. Build your confidence, sharpen your play, and meet people across the board.</p><div id="lessonContent" role="status">Loading classes…</div>';
  const view=++lessonView;
  try{const data=await api('lessons');if(view!==lessonView||!document.querySelector('#lessonContent'))return;const classes=data.lessons.filter(t=>t.start_at>Date.now());const teachers=[...new Map(classes.map(t=>[t.details.teacher==='Teacher to be announced'?t.id:t.details.teacher,t])).values()];
    document.querySelector('#lessonContent').innerHTML='<h2>Upcoming classes</h2><p>Individual sessions. All dates and times are Malaysia time.</p>'+(classes.length?'<div class="lesson-grid">'+classes.map(t=>'<article class="panel lesson-card">'+lessonImage(t.details.classPhoto,t.title+' — class photo')+'<span class="tag">'+esc((t.details.provisional?'Sample · ':'')+t.details.level)+' · 18+</span><h2>'+esc(t.title)+'</h2><p>'+esc(tournamentDate(t.start_at))+' MYT</p>'+lessonFacts(t)+'<p>'+esc(tournamentStatus(t))+'</p><button class="primary" data-lesson="'+esc(t.id)+'">View class</button></article>').join('')+'</div>':'<section class="panel lesson-empty"><h3>Your next move starts here.</h3><p>Our adult lesson schedule is coming soon. Get in touch to tell us your level and preferred times.</p><a class="primary" href="'+lessonEnquiry+'" target="_blank" rel="noopener noreferrer">Enquire about lessons</a></section>')+'<section class="lesson-paths"><div class="eyebrow">Where would you like to start?</div><h2>A place for every stage.</h2><div class="lesson-grid">'+[['01','Learn the Basics','New to chess? Start with the pieces, rules and your first complete game.'],['02','Build Your Game','Develop opening habits, spot threats and make a plan for your next move.'],['03','Strategy & Tactics','Explore combinations, positional decisions and practical endgames.']].map(([n,h,p])=>'<article class="lesson-path"><span>'+n+'</span><h3>'+h+'</h3><p>'+p+'</p></article>').join('')+'</div><p>These are learning pathways. Check each scheduled class for its specific topic and level.</p></section><section class="lesson-paths"><h2>Meet the teachers</h2>'+(teachers.length?'<div class="lesson-grid">'+teachers.map(lessonTeacher).join('')+'</div>':'<div class="lesson-grid">'+['Beginner','Intermediate','Advanced'].map(level=>lessonTeacher({details:{teacher:'Teacher to be announced',level,teacherBio:'Meet your teacher here once our class details are confirmed.'}})).join('')+'</div>')+'</section><section class="panel lesson-enquiry"><div><h2>Interested in future lessons?</h2><p>Tell us about your chess experience and when you would like to join.</p></div><a class="primary" href="'+lessonEnquiry+'" target="_blank" rel="noopener noreferrer">Enquire on WhatsApp</a></section>';
    document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>lessonDetail(classes.find(t=>t.id===b.dataset.lesson)));
  }catch(e){const target=document.querySelector('#lessonContent');if(target){target.innerHTML='<p class="error">'+esc(e.message)+'</p><button id="retryLessons" class="secondary">Retry</button>';document.querySelector('#retryLessons').onclick=lessonsPage}}
}
function lessonDetail(t){
  lessonView++;window.scrollTo({top:0,behavior:'instant'});const d=t.details;
  app.innerHTML='<button id="allLessons" class="secondary">All lessons</button><div class="tournament-heading"><div class="eyebrow">'+esc(d.level)+' · Adults 18+</div><h1>'+esc(t.title)+'</h1><p>'+esc(tournamentDate(t.start_at))+' MYT · '+d.duration+' minutes</p>'+(d.provisional?'<p class="lesson-provisional"><strong>Sample lesson · Provisional details</strong><br>The date, time, teacher, location and fee are provisional. Your booking is saved for the organisers. Check back for confirmed details before making plans.</p>':'')+'</div><div class="tournament-detail-layout"><section><div class="panel"><h2>Class details</h2>'+lessonImage(d.classPhoto,t.title+' — class photo')+lessonFacts(t)+tournamentLink(d.map,'Venue map')+'</div>'+[['What you’ll learn',d.outcomes],['Lesson outline',d.outline],['Before you join',d.prerequisites],['What to bring',d.bring]].filter(x=>x[1]).map(([h,p])=>'<section class="tournament-notes"><h2>'+h+'</h2><p>'+esc(p)+'</p></section>').join('')+'<section class="lesson-paths"><h2>Your teacher</h2>'+lessonTeacher(t)+'</section></section><section class="panel tournament-signup"><h2>'+(t.canRegister?'Book your place.':esc(tournamentStatus(t)))+'</h2><p>'+esc(tournamentStatus(t))+'</p>'+(t.canRegister?'<form id="lessonSignup"><label for="studentName">Name</label><input id="studentName" name="name" autocomplete="name" required minlength="2" maxlength="80"><label for="studentEmail">Email</label><input id="studentEmail" name="email" autocomplete="email" type="email" required maxlength="254"><label for="studentPhone">Phone (optional)</label><input id="studentPhone" name="phone" autocomplete="tel" type="tel" maxlength="30"><label for="studentExperience">Chess experience</label><select id="studentExperience" name="experience" required><option value="">Choose your experience</option><option>Complete beginner</option><option>Know the rules</option><option>Casual player</option><option>Regular / competitive player</option><option>Returning after a break</option></select><label class="tournament-consent"><input name="adult" type="checkbox" required><span>I am aged 18 or over.</span></label><label class="tournament-consent"><input name="consent" type="checkbox" required><span>I agree to share these details with chessynight to organise this lesson.</span></label><button class="primary" type="submit">Book a place</button><p><small>One booking per email. Lesson fees are arranged with the organiser; no payment is taken here. Contact the club to change or cancel a booking.</small></p><p id="lessonSignupStatus" role="status"></p></form>':'<a class="secondary" href="'+lessonEnquiry+'" target="_blank" rel="noopener noreferrer">Contact the club</a>')+'</section></div>';
  document.querySelector('#allLessons').onclick=lessonsPage;const form=document.querySelector('#lessonSignup');if(form)form.onsubmit=async e=>{e.preventDefault();const button=e.submitter,status=document.querySelector('#lessonSignupStatus');button.disabled=true;status.textContent='Saving your booking…';try{const values=Object.fromEntries(new FormData(form));const response=await api('lessons/register',{...values,lessonId:t.id,consent:values.consent==='on',adult:values.adult==='on'});form.innerHTML='<h3>Your place is booked.</h3><p role="status">'+esc(response.message)+'</p><p>'+esc(t.title)+'<br>'+esc(tournamentDate(t.start_at))+' MYT<br>'+esc(t.venue)+'<br>Teacher: '+esc(d.teacher)+'</p><a class="secondary" href="'+lessonEnquiry+'" target="_blank" rel="noopener noreferrer">Contact the club</a>'}catch(err){status.textContent=err.message;status.classList.add('error');button.disabled=false}};
}
document.querySelector('#lessonsNav').onclick=lessonsPage;
