import {practiceAPI} from './practice.js';
import {pushAPI} from './push.js';
import {isPagesRequest,withPagesCors} from './pages-cors.js';
import {lessonAPI} from './lessons.js';
import {tournamentAPI} from './tournaments.js';
import {Chess} from 'chess.js';
import {page,adminPage,chessSource,posterBase64,logoBase64,ladiesPosterBase64,eventPosters,pwaFiles} from './assets.js';
import {json,db,isAdmin,adminRole,today,currentSet,classic,lineMove,adminAPI,rankingKey,seedClubEvent,registerEvent} from './content.js';
const worker={async fetch(req,env){const url=new URL(req.url),path=url.pathname;try{
if(Object.hasOwn(pwaFiles,path)){const f=pwaFiles[path];return new Response(f.binary?Uint8Array.from(atob(f.data),c=>c.charCodeAt(0)):f.data,{headers:{'Content-Type':f.mime,'Cache-Control':'no-cache'}})}
if(path.startsWith('/posters/')){const name=path.slice(9);if(!Object.hasOwn(eventPosters,name))return new Response('Not found',{status:404});const poster=eventPosters[name];return new Response(Uint8Array.from(atob(poster.data),c=>c.charCodeAt(0)),{headers:{'Content-Type':poster.mime,'Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}})}
if(req.method==='POST'){if(!req.headers.get('Content-Type')?.startsWith('application/json'))return json({error:'JSON required.'},415);if(req.headers.get('Origin')&&req.headers.get('Origin')!==url.origin&&!isPagesRequest(req))return json({error:'Request origin rejected.'},403);if(Number(req.headers.get('Content-Length'))>(path==='/api/admin/photo'?6000000:250000))return json({error:'Import too large.'},413)}
if(path.startsWith('/media/')){const key=path.slice(7);if(!/^[a-f0-9-]{36}\.webp$/.test(key))return new Response('Not found',{status:404});if(!env.PHOTOS)return json({error:'Photo storage unavailable.'},503);const image=await env.PHOTOS.get(key);if(!image)return new Response('Not found',{status:404});return new Response(image.body,{headers:{'Content-Type':'image/webp','Cache-Control':'public,max-age=86400','X-Content-Type-Options':'nosniff'}})}
if(path==='/club-poster.webp'){const bytes=Uint8Array.from(atob(posterBase64),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'Content-Type':'image/webp','Cache-Control':'public,max-age=86400'}})}
if(path==='/chessynight-logo.png'){const bytes=Uint8Array.from(atob(logoBase64),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'Content-Type':'image/png','Cache-Control':'public,max-age=86400'}})}
if(path==='/ladies-chessy-vol-2.png'){const bytes=Uint8Array.from(atob(ladiesPosterBase64),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'Content-Type':'image/png','Cache-Control':'public,max-age=86400'}})}
if(path==='/api/register'&&req.method==='POST')return await registerEvent(req,env);
if(path==='/chess.js')return new Response(chessSource,{headers:{'Content-Type':'text/javascript'}});
if(path==='/favicon.svg')return new Response('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#102b22"/><text x="10" y="50" font-size="50" fill="#e6bb69">♞</text></svg>',{headers:{'Content-Type':'image/svg+xml'}});
if(path.startsWith('/api/lessons')||path.startsWith('/api/admin/lesson'))return await lessonAPI(req,env,path);
if(path.startsWith('/api/tournaments')||path.startsWith('/api/admin/tournament'))return await tournamentAPI(req,env,path);
if(path.startsWith('/api/practice/'))return await practiceAPI(req,env,path);
if(path.startsWith('/api/push/')||path==='/api/admin/push')return await pushAPI(req,env,path);
if(path.startsWith('/api/admin/'))return await adminAPI(req,env,path);
if(path==='/api/content'){await seedClubEvent(env);const set=await currentSet(env);const sets=(await db(env).prepare('SELECT id,title,date FROM challenge_sets WHERE published=1 AND date<=? ORDER BY date DESC,updated DESC LIMIT 30').bind(today()).all()).results;const posts=(await db(env).prepare('SELECT * FROM posts WHERE published=1 AND date<=? ORDER BY date DESC,updated DESC LIMIT 100').bind(today()).all()).results;return json({set:{id:set.id,title:set.title,date:set.id==='woodpecker-puzzles'?'':set.date,count:set.puzzles.length,fen:set.puzzles[0].fen},sets:[...sets.map(s=>s.id==='woodpecker-puzzles'?{...s,date:''}:s),{id:'classic',title:'CHESSYNIGHT Start Set',date:''}],posts,admin:Boolean(await adminRole(req,env)),today:today()})}
if(path==='/api/start'&&req.method==='POST'){const b=await req.json();const nickname=typeof b.nickname==='string'?b.nickname.trim():'';if(nickname.length<2||nickname.length>24||/[\u0000-\u001f]/.test(nickname))return json({error:'Use a nickname between 2 and 24 characters.'},400);const set=await currentSet(env,b.challenge);if(!set)return json({error:'This puzzle set is not available.'},404);const id=crypto.randomUUID(),state=set.puzzles.map(()=>({step:0,moves:[],solved:false,failed:false}));await db(env).prepare('INSERT INTO attempts (id,nickname,started,challenge,snapshot,state) VALUES (?,?,?,?,?,?)').bind(id,nickname,Date.now(),await rankingKey(set),JSON.stringify(set.puzzles),JSON.stringify(state)).run();return json({id,title:set.title,puzzles:set.puzzles.map(p=>({fen:p.fen,title:p.title,moves:Math.ceil(p.solution.length/2)}))})}
if(path==='/api/move'&&req.method==='POST'){const b=await req.json();if(typeof b.id!=='string'||!Number.isInteger(b.index))return json({error:'Invalid move request.'},400);const a=await db(env).prepare('SELECT * FROM attempts WHERE id=?').bind(b.id).first();if(!a||!a.snapshot||a.finished!==null)return json({error:'Attempt unavailable.'},409);const puzzles=JSON.parse(a.snapshot),state=JSON.parse(a.state),p=puzzles[b.index],s=state[b.index];if(s&&b.request&&s.request===b.request)return json(s.result);if(!p||!s||s.solved||s.failed)return json({error:'Puzzle already finished or unavailable.'},409);const c=new Chess(p.fen);for(const m of s.moves)lineMove(c,m);if(b.skip)s.failed=true;else{let moved;try{moved=lineMove(c,b.move)}catch{return json({error:'That move is not legal.'},400)}const u=moved.from+moved.to+(moved.promotion||'');s.moves.push(u);if(u!==p.solution[s.step]&&!(p.mate&&c.isCheckmate()))s.failed=true;else{s.step++;if(s.step>=p.solution.length||p.mate&&c.isCheckmate())s.solved=true;else{const reply=p.solution[s.step++];lineMove(c,reply);s.moves.push(reply)}}}
const response={fen:c.fen(),solved:s.solved,failed:s.failed,score:state.filter(s=>s.solved).length*100,done:s.solved||s.failed};if(typeof b.request==='string'&&b.request.length<300){s.request=b.request;s.result=response}const result=await db(env).prepare('UPDATE attempts SET state=? WHERE id=? AND state=? AND finished IS NULL').bind(JSON.stringify(state),b.id,a.state).run();if(result.meta?.changes===0)return json({error:'Another move is already being saved. Please retry.'},409);return json(response)}
if(path==='/api/finish'&&req.method==='POST'){const b=await req.json();if(typeof b.id!=='string')return json({error:'Invalid result.'},400);const a=await db(env).prepare('SELECT * FROM attempts WHERE id=?').bind(b.id).first();if(!a)return json({error:'Attempt not found.'},404);const list=a.snapshot?JSON.parse(a.snapshot):classic().puzzles;let score=0;if(a.finished===null){if(a.state){const state=JSON.parse(a.state);if(state.some(s=>!s.solved&&!s.failed))return json({error:'Finish or skip every puzzle first.'},400);score=state.filter(s=>s.solved).length*100}else{for(let i=0;i<list.length;i++)try{const c=new Chess(list[i].fen);lineMove(c,b.answers?.[i]);if(c.isCheckmate())score+=100}catch{}}const now=Date.now();await db(env).prepare('UPDATE attempts SET finished=?,score=?,elapsed=? WHERE id=? AND finished IS NULL').bind(now,score,Math.max(0,now-a.started),b.id).run()}
const saved=await db(env).prepare('SELECT * FROM attempts WHERE id=?').bind(b.id).first();const better=await db(env).prepare('SELECT COUNT(*) AS n FROM attempts WHERE challenge=? AND finished IS NOT NULL AND (score>? OR (score=? AND elapsed<?) OR (score=? AND elapsed=? AND finished<?))').bind(saved.challenge,saved.score,saved.score,saved.elapsed,saved.score,saved.elapsed,saved.finished).first();return json({score:saved.score,elapsed:saved.elapsed,rank:better.n+1,count:list.length})}
if(path==='/api/leaderboard'){const set=await currentSet(env,url.searchParams.get('challenge'));if(!set)return json({error:'Challenge unavailable.'},404);const result=await db(env).prepare('SELECT nickname,score,elapsed FROM attempts WHERE challenge=? AND finished IS NOT NULL ORDER BY score DESC,elapsed ASC,finished ASC LIMIT 100').bind(await rankingKey(set)).all();return json({rows:result.results,title:set.title,count:set.puzzles.length})}
if(path.startsWith('/api/'))return json({error:'Not found'},404);
if(path==='/admin'){if(!req.headers.get('oai-authenticated-user-id'))return Response.redirect(url.origin+'/signin-with-chatgpt?return_to=%2Fadmin',302);if(!await adminRole(req,env))return new Response('You do not have access to this admin area.',{status:403});return new Response(adminPage,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store'}})}
if(path!=='/')return new Response('Not found',{status:404});return new Response(page,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
}catch(e){console.error(e);return json({error:'Could not load or save content. Please try again.'},503)}}};

export default {fetch(req,env){return withPagesCors(req,env,(request,bindings)=>worker.fetch(request,bindings))}};
