import {Chess} from 'chess.js';
import {db,json,currentSet,lineMove} from './content.js';
const newState=list=>({index:0,completed:false,results:list.map(()=>({step:0,moves:[],solved:false,skipped:false,mistake:false}))});
function view(row){const puzzles=JSON.parse(row.snapshot),state=JSON.parse(row.state);const result=state.results[state.index],board=new Chess(puzzles[state.index].fen);for(const move of result.moves)lineMove(board,move);return {id:row.id,collection:row.collection,title:row.collection==='classic'?'Chessynight Start Set':row.title,nickname:row.nickname,started:row.started,index:state.index,completed:state.completed,fen:board.fen(),done:result.solved||result.skipped,solved:state.results.map(s=>s.solved),mistakes:state.results.filter(s=>s.mistake||s.skipped).length,puzzles:puzzles.map(p=>({fen:p.fen,title:p.title}))}}
async function create(env,collection,title,nickname,puzzles){const id=crypto.randomUUID(),now=Date.now(),state=JSON.stringify(newState(puzzles));await db(env).prepare('INSERT INTO practice_sessions (id,collection,title,nickname,snapshot,state,started,updated) VALUES (?,?,?,?,?,?,?,?)').bind(id,collection,title,nickname,JSON.stringify(puzzles),state,now,now).run();return {id,collection,title,nickname,snapshot:JSON.stringify(puzzles),state,started:now}}
export async function practiceAPI(req,env,path){if(req.method!=='POST')return json({error:'Method not allowed.'},405);const b=await req.json();if(path==='/api/practice/start'){const set=await currentSet(env,b.challenge);if(!set)return json({error:'This puzzle collection is unavailable.'},404);const list=[...set.puzzles];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return json(view(await create(env,set.id,set.title,String(b.nickname||'Practice player').trim().slice(0,24),list.slice(0,10))))}
 if(typeof b.id!=='string'||!/^[a-f0-9-]{36}$/.test(b.id))return json({error:'Practice session unavailable.'},404);const row=await db(env).prepare('SELECT * FROM practice_sessions WHERE id=?').bind(b.id).first();if(!row)return json({error:'Practice session unavailable.'},404);const state=JSON.parse(row.state),puzzles=JSON.parse(row.snapshot);
 if(path==='/api/practice/resume')return json(view(row));
 if(path==='/api/practice/retry'){if(!state.completed)return json({error:'Finish this practice session before reviewing mistakes.'},409);const missed=puzzles.filter((_,i)=>state.results[i].mistake||state.results[i].skipped);if(!missed.length)return json({error:'No missed puzzles in this session.'},409);return json(view(await create(env,row.collection,row.title,row.nickname,missed)))}
 if(path==='/api/practice/advance'){if(state.completed||b.index===state.index-1)return json(view(row));if(b.index!==state.index||!Number.isInteger(b.index))return json({error:'Resume your latest saved position.'},409);const s=state.results[state.index];if(!s.solved&&!s.skipped)return json({error:'Solve or skip this puzzle first.'},409);if(state.index===puzzles.length-1)state.completed=true;else state.index++;const updated=JSON.stringify(state);const result=await db(env).prepare('UPDATE practice_sessions SET state=?,updated=? WHERE id=? AND state=?').bind(updated,Date.now(),row.id,row.state).run();if(result.meta?.changes===0)return json({error:'Your progress changed. Resume your saved session.'},409);return json(view({...row,state:updated}))}
 if(path==='/api/practice/move'){if(state.completed||b.index!==state.index)return json({error:'Resume your latest saved position.'},409);const p=puzzles[state.index],s=state.results[state.index];if(b.request&&b.request===s.request)return json(s.result);if(s.solved||s.skipped)return json({error:'This puzzle is finished.'},409);const board=new Chess(p.fen);for(const move of s.moves)lineMove(board,move);let incorrect=false;if(b.skip){s.skipped=true;s.mistake=true}else{let move;try{move=lineMove(board,b.move)}catch{return json({error:'That move is not legal.'},400)}const uci=move.from+move.to+(move.promotion||'');if(uci!==p.solution[s.step]&&!(p.mate&&board.isCheckmate())){s.mistake=true;incorrect=true;board.undo()}else{s.moves.push(uci);s.step++;if(s.step>=p.solution.length||p.mate&&board.isCheckmate())s.solved=true;else{const reply=p.solution[s.step++];lineMove(board,reply);s.moves.push(reply)}}}const response={fen:board.fen(),solved:s.solved,failed:s.skipped,incorrect,score:state.results.filter(s=>s.solved).length*100,done:s.solved||s.skipped};if(typeof b.request==='string'&&b.request.length<300){s.request=b.request;s.result=response}const updated=JSON.stringify(state);const result=await db(env).prepare('UPDATE practice_sessions SET state=?,updated=? WHERE id=? AND state=?').bind(updated,Date.now(),row.id,row.state).run();if(result.meta?.changes===0)return json({error:'Your progress changed. Resume your saved session.'},409);return json(response)}
 return json({error:'Not found'},404);
}
