let practiceMode=false;
function practiceSaved(){try{const saved=JSON.parse(localStorage.getItem('chessynightPractice')||'{}');return saved&&typeof saved==='object'&&!Array.isArray(saved)?saved:{}}catch{return {}}}
function savePractice(session){try{const saved=practiceSaved();saved[session.collection]={id:session.id,title:session.title,completed:session.completed,mistakes:session.mistakes||0};localStorage.setItem('chessynightPractice',JSON.stringify(saved))}catch{}}
function practiceButtons(set){const saved=practiceSaved()[set.id];return '<button class="secondary" type="button" data-practice="'+esc(set.id)+'">Quick practice · up to 10 puzzles</button>'+(saved&&!saved.completed?'<button class="text-button" type="button" data-resume="'+esc(set.id)+'">Continue saved practice &rarr;</button>':'')+(saved?.completed&&saved.mistakes?'<button class="text-button" type="button" data-review="'+esc(set.id)+'">Retry missed puzzles &rarr;</button>':'')}
function bindPractice(){document.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>startPractice(b.dataset.practice));document.querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>startPractice(b.dataset.resume,'resume'));document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>startPractice(b.dataset.review,'retry'))}
async function startPractice(collection,action='start'){const buttons=[...document.querySelectorAll('.puzzle-set-card button')];buttons.forEach(b=>b.disabled=true);try{const saved=practiceSaved()[collection];const session=await api('practice/'+action,action==='start'?{challenge:collection,nickname:document.querySelector('#nickname')?.value.trim()||nick||'Practice player'}:{id:saved?.id||id});applyPractice(session)}catch(error){const message=document.querySelector('#error');if(message)message.textContent=error.message;buttons.forEach(b=>b.disabled=false)}}
function applyPractice(session){practiceMode=true;savePractice(session);id=session.id;challenge=session.collection;challengeTitle=session.title;nick=session.nickname;puzzles=session.puzzles;index=session.index;solved=session.solved;finished=session.completed;started=session.started;clearInterval(timer);if(session.completed){practiceSummary(session);return}game=new Chess(session.fen);playerColor=new Chess(puzzles[index].fen).turn();selected=null;lastMove=[];locked=session.done;renderPractice();if(locked){document.querySelector('#skip').classList.add('hidden');document.querySelector('#next').classList.remove('hidden');document.querySelector('#status').textContent=solved[index]?'Solved. Continue when you’re ready.':'Skipped. Continue when you’re ready.'}}
function renderPractice(){app.className='game';app.innerHTML='<div class="layout"><div id="board">'+board(game,true)+'</div><div class="panel"><div class="eyebrow">Practice · '+esc(challengeTitle)+' · Puzzle '+(index+1)+'</div><h1>'+(playerColor==='w'?'White':'Black')+' to move.</h1><p>'+esc(puzzles[index].title||'Find the best move')+'</p><p class="status" id="status" role="status">Select a piece, then its destination. You can try again after a mistake.</p><div class="actions"><button class="secondary" id="skip">Skip puzzle</button><button class="primary hidden" id="next">'+(index===puzzles.length-1?'Finish practice':'Next puzzle')+'</button><button class="text-button" id="pausePractice">Save & leave</button></div><p><small>Each move is saved. Practice does not affect the leaderboard. Resume on this browser and device.</small></p><p id="error" class="error" role="alert"></p></div></div>';bind();document.querySelector('#skip').onclick=()=>submitMove(null,true);document.querySelector('#next').onclick=nextPractice;document.querySelector('#pausePractice').onclick=home}
async function nextPractice(){const button=document.querySelector('#next');button.disabled=true;try{const session=await api('practice/advance',{id,index});applyPractice(session)}catch(error){document.querySelector('#status').textContent=error.message;button.disabled=false}}
function practiceSummary(session){app.className='';app.innerHTML='<section class="result panel"><div class="eyebrow">'+esc(session.title)+' · Practice complete</div><h1>Good practice. Keep going.</h1><p>'+session.solved.filter(Boolean).length+' puzzles solved. '+session.mistakes+' marked for review.</p><p>Your practice stays separate from timed challenge rankings.</p><div class="actions" style="justify-content:center">'+(session.mistakes?'<button class="primary" id="reviewPractice">Retry missed puzzles</button>':'')+'<button class="secondary" id="morePractice">Choose a collection</button></div><p id="error" class="error" role="alert"></p></section>';document.querySelector('#morePractice').onclick=home;const retry=document.querySelector('#reviewPractice');if(retry)retry.onclick=async()=>{retry.disabled=true;try{applyPractice(await api('practice/retry',{id:session.id}))}catch(error){document.querySelector('#error').textContent=error.message;retry.disabled=false}}}
