import {json,db,adminRole,rolePermissions} from './content.js';
const encode=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const decode=value=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export function validEndpoint(endpoint){try{const u=new URL(endpoint);return endpoint.length<3000&&u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&((u.hostname==='fcm.googleapis.com'&&/^\/fcm\/send\/[A-Za-z0-9_:-]+$/.test(u.pathname))||(u.hostname==='updates.push.services.mozilla.com'&&u.pathname.startsWith('/wpush/')))}catch{return false}}
async function sendPush(endpoint,env){const publicBytes=decode(env.PUSH_PUBLIC_KEY);const key=await crypto.subtle.importKey('jwk',{kty:'EC',crv:'P-256',x:encode(publicBytes.slice(1,33)),y:encode(publicBytes.slice(33)),d:env.PUSH_PRIVATE_KEY},{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const text=new TextEncoder();const head=encode(text.encode(JSON.stringify({typ:'JWT',alg:'ES256'})));const payload=encode(text.encode(JSON.stringify({aud:new URL(endpoint).origin,exp:Math.floor(Date.now()/1000)+3600,sub:'mailto:kishelraj@gmail.com'})));const unsigned=head+'.'+payload;const signature=encode(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,text.encode(unsigned)));return fetch(endpoint,{method:'POST',redirect:'error',headers:{Authorization:'vapid t='+unsigned+'.'+signature+', k='+env.PUSH_PUBLIC_KEY,TTL:'3600',Urgency:'normal'},signal:AbortSignal.timeout(10000)})}
export async function pushAPI(req,env,path){
 if(path==='/api/push/config'&&req.method==='GET')return json({publicKey:env.PUSH_PUBLIC_KEY||null});
 if(path==='/api/push/latest'&&req.method==='GET'){const row=await db(env).prepare('SELECT id,title,body,url FROM push_alerts ORDER BY created DESC LIMIT 1').first();return json(row||{title:'chessynight',body:'There’s something new at the club.',url:'https://kishelraj.github.io/Chessynight/'});}
 if(path==='/api/push/subscribe'&&req.method==='POST'){if(!env.PUSH_PUBLIC_KEY||!env.PUSH_PRIVATE_KEY)return json({error:'Notifications are not ready yet.'},503);const b=await req.json();if(!validEndpoint(b.endpoint))return json({error:'Unsupported notification service.'},400);await db(env).prepare('INSERT OR IGNORE INTO push_subscriptions (endpoint,created) VALUES (?,?)').bind(b.endpoint,Date.now()).run();return json({message:'Notifications enabled.'});}
 const role=await adminRole(req,env);if(!role||!rolePermissions[role].includes('events'))return json({error:'Your role cannot send notifications.'},403);
 if(path==='/api/admin/push'&&req.method==='GET'){const row=await db(env).prepare('SELECT COUNT(*) AS count FROM push_subscriptions').first();return json({count:row.count,ready:Boolean(env.PUSH_PUBLIC_KEY&&env.PUSH_PRIVATE_KEY)});}
 if(path==='/api/admin/push'&&req.method==='POST'){if(!env.PUSH_PUBLIC_KEY||!env.PUSH_PRIVATE_KEY)return json({error:'Notifications are not configured.'},503);const b=await req.json();if(typeof b.title!=='string'||!b.title.trim()||b.title.length>80||typeof b.body!=='string'||!b.body.trim()||b.body.length>200)return json({error:'Use a title up to 80 characters and a message up to 200.'},400);const url=b.url||'https://kishelraj.github.io/Chessynight/';try{const u=new URL(url);if(u.origin!=='https://kishelraj.github.io'||!u.pathname.startsWith('/Chessynight/'))throw Error()}catch{return json({error:'Link to the chessynight GitHub website.'},400)}const recent=await db(env).prepare('SELECT created FROM push_alerts ORDER BY created DESC LIMIT 1').first();if(recent&&Date.now()-recent.created<60000)return json({error:'Please wait a minute before sending another alert.'},429);const rows=(await db(env).prepare('SELECT endpoint FROM push_subscriptions LIMIT 1000').all()).results;await db(env).prepare('INSERT INTO push_alerts (id,title,body,url,created) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),b.title.trim(),b.body.trim(),url,Date.now()).run();let sent=0,failed=0;for(let i=0;i<rows.length;i+=20)await Promise.all(rows.slice(i,i+20).map(async row=>{try{const response=await sendPush(row.endpoint,env);if(response.ok)sent++;else{failed++;if([404,410].includes(response.status))await db(env).prepare('DELETE FROM push_subscriptions WHERE endpoint=?').bind(row.endpoint).run()}}catch{failed++}}));return json({message:'Push service accepted '+sent+' alert(s). '+failed+' failed.',sent,failed});}
 return json({error:'Not found'},404);
}
