let tournamentView=0;
const tournamentDate=value=>new Intl.DateTimeFormat('en-MY',{timeZone:'Asia/Kuala_Lumpur',weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));
const tournamentLink=(url,label)=>url&&/^https:\/\//.test(url)?'<a class="secondary" target="_blank" rel="noopener noreferrer" href="'+esc(url)+'">'+label+'</a>':'';
function tournamentStatus(t){return t.start_at<=Date.now()?'Registration ended':t.details.manuallyFull||!t.available?'Full':!t.registration_open?'Registration closed':t.details.registrationOpens>Date.now()?'Registration opens '+tournamentDate(t.details.registrationOpens)+' MYT':'Registration open · '+t.available+' places available'}
function tournamentHighlights(t){const d=t.details;return '<article class="tournament-news-item"><h3>'+esc(t.title)+'</h3>'+([['Winner',d.winner],['Runner-up',d.runnerUp],['Third place',d.thirdPlace]].filter(x=>x[1]).map(([label,name])=>'<div class="tournament-podium"><span>'+label+'</span><strong>'+esc(name)+'</strong></div>').join(''))+(d.news?'<p class="tournament-recap">'+esc(d.news)+'</p>':'')+((d.photos||[]).length?'<div class="tournament-photos">'+d.photos.map(photo=>'<figure><a href="'+esc(tournamentPhotoURL(photo.url))+'" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="'+esc(tournamentPhotoURL(photo.url))+'" alt="'+esc(photo.caption||t.title+' tournament photo')+'"></a>'+(photo.caption?'<figcaption>'+esc(photo.caption)+'</figcaption>':'')+'</figure>').join('')+'</div>':'')+'</article>'}
function tournamentPhotoURL(url){return typeof assetURL==='function'?assetURL(url):url}
function tournamentNews(tournaments){const news=tournaments.filter(t=>t.details.news||t.details.winner||t.details.runnerUp||t.details.thirdPlace||t.details.photos?.length).sort((a,b)=>b.updated-a.updated);return '<aside class="panel tournament-news"><div class="eyebrow">Around the boards</div><h2>Tournament news</h2>'+(news.length?news.map(tournamentHighlights).join(''):'<section class="tournament-news-empty"><h3>Meet the winners.</h3><p>Results and winner announcements will appear here after our tournaments.</p><div class="tournament-photo-space"><strong>Photo highlights</strong><p>Memorable games, podium moments, and familiar faces from tournament night.</p></div></section>')+'</aside>'}
async function tournamentsPage(){
  if(!leave())return;clearInterval(timer);clearInterval(eventTimer);activeNav('tournamentsNav');document.title='CHESSYNIGHT — Tournaments';app.className='tournaments-page';
  app.innerHTML='<div class="eyebrow">Over the board. In good company.</div><h1>Tournaments.</h1><p>Find your next in-person competition. All times are Malaysia time.</p><div id="tournamentContent" role="status">Loading tournaments…</div>';
  const view=++tournamentView;
  try{const d=await api('tournaments');if(view!==tournamentView||!document.querySelector('#tournamentContent'))return;
    const upcoming=d.tournaments.filter(t=>t.start_at>Date.now()),past=d.tournaments.filter(t=>t.start_at<=Date.now()).reverse();
    const card=t=>'<article class="panel tournament-card"><span class="tag">'+esc((t.details.rules?.startsWith('PROVISIONAL EVENT')?'Provisional · ':'')+tournamentStatus(t))+'</span><h2>'+esc(t.title)+'</h2><p>'+esc(tournamentDate(t.start_at))+' MYT<br>'+esc(t.venue)+'</p><div class="tournament-register-first"><strong>'+esc(tournamentStatus(t))+'</strong>'+(t.canRegister?'<button class="primary" data-register-tournament="'+esc(t.id)+'">Register now</button>':'')+'</div><dl class="tournament-facts"><div><dt>Entry</dt><dd>'+esc(t.details.fee)+'</dd></div><div><dt>Time control</dt><dd>'+esc(t.details.timeControl)+'</dd></div><div><dt>Format</dt><dd>'+esc(t.details.format)+' · '+t.details.rounds+' rounds</dd></div></dl><button class="primary" data-tournament="'+esc(t.id)+'">View tournament</button></article>';
    document.querySelector('#tournamentContent').innerHTML='<h2 class="tournament-section-title">Upcoming tournaments</h2>'+(upcoming.length?'<div class="tournament-grid">'+upcoming.map(card).join('')+'</div>':'<section class="panel tournament-empty"><h2>The next tournament starts here.</h2><p>Dates and venues will appear here when registration opens. Until then, join us for a casual club night.</p><button class="primary" id="tournamentEvents">Explore club events</button></section>')+(past.length?'<h2 class="tournament-section-title">Past tournaments</h2><div class="tournament-grid">'+past.map(card).join('')+'</div>':'');
    const tournamentContent=document.querySelector('#tournamentContent');tournamentContent.innerHTML='<div class="tournament-list-and-news"><div>'+tournamentContent.innerHTML+'</div>'+tournamentNews(d.tournaments)+'</div>';
    document.querySelector('#tournamentEvents')?.addEventListener('click',updates);
    document.querySelectorAll('[data-register-tournament]').forEach(b=>b.onclick=()=>{tournamentDetail(d.tournaments.find(t=>t.id===b.dataset.registerTournament));document.querySelector('#tournamentSignup')?.scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#playerName')?.focus({preventScroll:true})});
    document.querySelectorAll('[data-tournament]').forEach(b=>b.onclick=()=>tournamentDetail(d.tournaments.find(t=>t.id===b.dataset.tournament)));
  }catch(e){const el=document.querySelector('#tournamentContent');if(el){el.innerHTML='<p class="error">'+esc(e.message)+'</p><button class="secondary" id="retryTournaments">Retry</button>';document.querySelector('#retryTournaments').onclick=tournamentsPage}}
}
function tournamentDetail(t){
  tournamentView++;window.scrollTo({top:0,behavior:'instant'});const d=t.details;
  app.innerHTML='<button class="secondary" id="allTournaments">All tournaments</button><div class="tournament-heading"><div class="eyebrow">In-person tournament</div><h1>'+esc(t.title)+'</h1><p>'+esc(tournamentDate(t.start_at))+' MYT · '+esc(t.venue)+'</p></div><div class="tournament-detail-layout"><section><div class="panel"><h2>The details</h2><dl class="tournament-facts"><div><dt>Entry fee</dt><dd>'+esc(d.fee)+'</dd></div><div><dt>Time control</dt><dd>'+esc(d.timeControl)+'</dd></div><div><dt>Format</dt><dd>'+esc(d.format)+'</dd></div><div><dt>Rounds</dt><dd>'+d.rounds+'</dd></div><div><dt>Check-in</dt><dd>'+esc(d.checkIn?tournamentDate(d.checkIn)+' MYT':'Ask the organiser for arrival instructions')+'</dd></div><div><dt>Capacity</dt><dd>'+t.capacity+' players</dd></div></dl><div class="actions">'+tournamentLink(d.map,'Venue map')+tournamentLink(d.pairings,'Pairings & standings')+tournamentLink(d.results,'Final results')+'</div></div>'+[['Who can play',d.eligibility],['Rules & arrival information',d.rules],['Prizes',d.prizes]].filter(x=>x[1]).map(([h,v])=>'<section class="tournament-notes"><h2>'+h+'</h2><p>'+esc(v)+'</p></section>').join('')+'</section><section class="panel tournament-signup"><h2>'+(t.canRegister?'Take your seat.':esc(tournamentStatus(t)))+'</h2><p>'+esc(tournamentStatus(t))+'</p>'+(t.canRegister?'<form id="tournamentSignup"><label for="playerName">Player name</label><input id="playerName" name="name" required minlength="2" maxlength="80" autocomplete="name"><label for="playerEmail">Email</label><input id="playerEmail" name="email" type="email" required maxlength="254" autocomplete="email"><label for="playerPhone">Phone (optional)</label><input id="playerPhone" name="phone" type="tel" maxlength="30" autocomplete="tel"><label for="playerRating">Chess rating (optional)</label><input id="playerRating" name="rating" type="number" min="0" max="3500" step="1"><label class="tournament-consent"><input name="consent" type="checkbox" required> <span>I agree to share these details with CHESSYNIGHT to organise this tournament.</span></label><button class="primary" type="submit">Register for tournament</button><p><small>One entry per email. Any entry fee is handled by the organiser; this form does not take payment.</small></p><p id="tournamentSignupStatus" role="status"></p></form>':'<p>Contact the club for tournament enquiries.</p><a class="secondary" href="https://wa.me/60172188005" target="_blank" rel="noopener noreferrer">Contact the club</a>')+'</section></div>';
  app.insertAdjacentHTML('beforeend','<section class="tournament-detail-news">'+tournamentNews([t])+'</section>');
  document.querySelector('#allTournaments').onclick=tournamentsPage;
  const form=document.querySelector('#tournamentSignup');if(form)form.onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const status=document.querySelector('#tournamentSignupStatus');status.textContent='Saving your registration…';try{const fields=Object.fromEntries(new FormData(form));const response=await api('tournaments/register',{...fields,tournamentId:t.id,consent:fields.consent==='on'});form.innerHTML='<h3>You’re on the list.</h3><p role="status">'+esc(response.message)+'</p><p>'+esc(t.title)+'<br>'+esc(tournamentDate(t.start_at))+' MYT<br>'+esc(t.venue)+'</p>'}catch(err){status.textContent=err.message;status.classList.add('error');button.disabled=false}};
}
document.querySelector('#tournamentsNav').onclick=tournamentsPage;
async function openLinkedTournament(id){
  await tournamentsPage();if(!document.querySelector('#tournamentContent'))return;
  const button=[...document.querySelectorAll('[data-tournament]')].find(b=>b.dataset.tournament===id);
  if(button)button.click();
}
