let tournamentPhotos=[],tournamentId=null,tournamentAdminData={tournaments:[],canEdit:false,canCheckIn:false};
const localTournamentTime=v=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)).replace(' ','T'):'';
const tournamentInput=(id,label,type='text',required=false,max='')=>'<div><label for="t-'+id+'">'+label+'</label><input id="t-'+id+'" name="'+id+'" type="'+type+'" '+(required?'required ':'')+(max?'maxlength="'+max+'"':'')+'></div>';
const tournamentArea=document.createElement('section');tournamentArea.id='tournamentArea';tournamentArea.className='admin-layout hidden';
tournamentArea.innerHTML='<aside class="panel saved"><div class="section-head"><h2>Tournaments</h2><button class="secondary" id="newTournament">New tournament</button></div><div id="savedTournaments" role="status"></div></aside><div><section class="panel" id="tournamentEditor"><h2>Tournament editor</h2><p>Dates and times use Malaysia time. Drafts are only visible to the team.</p><form id="tournamentForm"><fieldset id="tournamentFields" style="border:0;padding:0;margin:0;min-width:0"><div class="tournament-admin-fields">'+tournamentInput('title','Tournament name','text',true,120)+tournamentInput('venue','Venue & address','text',true,200)+tournamentInput('start','First round','datetime-local',true)+tournamentInput('checkIn','Check-in opens','datetime-local')+tournamentInput('fee','Entry fee (e.g. RM 25 or Free)','text',true,120)+tournamentInput('capacity','Maximum players','number',true)+tournamentInput('format','Format (e.g. Swiss)','text',true,120)+tournamentInput('timeControl','Time control (e.g. 10+5)','text',true,120)+tournamentInput('rounds','Number of rounds','number',true)+tournamentInput('map','Venue map link','url',false,2000)+tournamentInput('pairings','Pairings & standings link','url',false,2000)+tournamentInput('results','Final results link','url',false,2000)+'<div class="wide"><label for="t-eligibility">Eligibility</label><textarea id="t-eligibility" maxlength="500" placeholder="Age groups, rating limits, or open to all"></textarea><label for="t-rules">Rules & arrival information</label><textarea id="t-rules" maxlength="5000"></textarea><label for="t-prizes">Prizes (optional)</label><textarea id="t-prizes" maxlength="1000"></textarea></div></div><label class="check"><input id="t-published" type="checkbox"> Publish tournament</label><label class="check"><input id="t-open" type="checkbox"> Accept registrations until the first round or capacity is reached</label><button class="primary" type="submit">Save tournament</button></fieldset><p id="tournamentSaveStatus" role="status"></p></form></section><section class="panel" style="margin-top:24px"><div class="section-head"><h2>Players & check-in</h2><button id="refreshTournamentEntries" class="secondary">Refresh players</button></div><div id="tournamentEntries" role="status">Save or select a tournament to view its players.</div></section></div>';
$('admin-main').append(tournamentArea);
const newsEditor=document.createElement('section');newsEditor.className='photo-editor';newsEditor.innerHTML='<h3>News, winners & photos</h3><p>Publish a recap and results here. These appear in the tournament news column when the tournament is published.</p>'+tournamentInput('winner','Winner','text',false,120)+tournamentInput('runnerUp','Runner-up','text',false,120)+tournamentInput('thirdPlace','Third place','text',false,120)+'<label for="t-news">News / tournament recap</label><textarea id="t-news" maxlength="3000"></textarea><label for="t-photoUpload">Tournament photos (up to 8)</label><input id="t-photoUpload" type="file" accept="image/jpeg,image/png,image/webp" multiple><div id="t-photoList"></div><p id="t-photoStatus" role="status"></p>';
$('tournamentFields').insertBefore(newsEditor,$('t-published').closest('label'));
function drawTournamentPhotos(){
  $('t-photoList').innerHTML=tournamentPhotos.map((p,i)=>'<div class="tournament-photo-edit"><img src="'+esc(p.url)+'" alt="Tournament photo '+(i+1)+'"><label>Photo caption<input data-t-caption="'+i+'" maxlength="200" value="'+esc(p.caption)+'"></label><button type="button" class="secondary" data-t-remove="'+i+'">Remove photo '+(i+1)+'</button></div>').join('');
  document.querySelectorAll('[data-t-caption]').forEach(input=>input.oninput=()=>{tournamentPhotos[Number(input.dataset.tCaption)].caption=input.value});
  document.querySelectorAll('[data-t-remove]').forEach(button=>button.onclick=()=>{tournamentPhotos.splice(Number(button.dataset.tRemove),1);drawTournamentPhotos()});
}
$('t-photoUpload').onchange=async e=>{
  const files=[...e.target.files];if(!files.length)return;
  if(tournamentPhotos.length+files.length>8){notice('t-photoStatus','Add up to eight photos.',true);e.target.value='';return}
  const photos=tournamentPhotos;const controls=[$('tournamentFields'),$('newTournament'),...document.querySelectorAll('[data-edit-tournament],#tabTournaments')];const disabled=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);
  try{for(const file of files){notice('t-photoStatus','Uploading '+file.name+'…');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15000000)throw Error('Use JPEG, PNG or WebP photos smaller than 15 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const result=await api('photo',{data:canvas.toDataURL('image/webp',.86).split(',')[1]});photos.push({url:result.url,caption:''});if(photos===tournamentPhotos)drawTournamentPhotos()}notice('t-photoStatus','Photos uploaded. Add captions and save the tournament to publish them.')}catch(err){notice('t-photoStatus',err.message,true)}finally{controls.forEach((c,i)=>c.disabled=disabled[i]);e.target.value=''}
};

const tournamentTab=document.createElement('button');tournamentTab.id='tabTournaments';tournamentTab.className='secondary';tournamentTab.textContent='Tournaments';$('tabPosts').after(tournamentTab);
for(const id of ['tabPuzzles','tabPosts'])$(id).addEventListener('click',()=>{tournamentArea.classList.add('hidden');tournamentTab.classList.remove('primary')});
tournamentTab.onclick=()=>{for(const id of ['puzzleArea','postArea'])$(id).classList.add('hidden');for(const id of ['tabPuzzles','tabPosts'])$(id).classList.remove('primary');tournamentArea.classList.remove('hidden');tournamentTab.classList.add('primary');loadTournaments()};
$('t-capacity').min='1';$('t-capacity').max='1000';$('t-rounds').min='1';$('t-rounds').max='30';
async function loadTournaments(){
  $('savedTournaments').textContent='Loading…';
  try{tournamentAdminData=await api('tournaments');$('tournamentFields').disabled=!tournamentAdminData.canEdit;$('newTournament').disabled=!tournamentAdminData.canEdit;
    $('savedTournaments').innerHTML=tournamentAdminData.tournaments.length?tournamentAdminData.tournaments.map(t=>'<button class="saved-row" data-edit-tournament="'+esc(t.id)+'"><b>'+esc(t.title)+'</b><span>'+esc(localTournamentTime(t.start_at).replace('T',' '))+' MYT · '+(t.published?'Published':'Draft')+'</span><span>'+t.registered+' / '+t.capacity+' players</span></button>').join(''):'<p>No tournaments yet. Create a draft to get started.</p>';
    document.querySelectorAll('[data-edit-tournament]').forEach(b=>b.onclick=()=>editTournament(b.dataset.editTournament));
    if(!tournamentAdminData.canEdit)notice('tournamentSaveStatus','Your role has read-only access to tournament details.');
  }catch(e){$('savedTournaments').textContent=e.message}
}
function newTournament(){tournamentId=null;tournamentPhotos=[];drawTournamentPhotos();$('tournamentForm').reset();$('tournamentEntries').textContent='Save this tournament to manage registrations.';notice('tournamentSaveStatus','New draft.');$('t-title').focus()}
function editTournament(id){const t=tournamentAdminData.tournaments.find(t=>t.id===id);if(!t)return;tournamentId=id;tournamentPhotos=structuredClone(t.details.photos||[]);drawTournamentPhotos();for(const k of ['title','venue','capacity'])$('t-'+k).value=t[k];$('t-start').value=localTournamentTime(t.start_at);$('t-checkIn').value=localTournamentTime(t.details.checkIn);for(const k of ['fee','format','timeControl','rounds','map','pairings','results','eligibility','rules','prizes','winner','runnerUp','thirdPlace','news'])$('t-'+k).value=t.details[k]||'';$('t-published').checked=Boolean(t.published);$('t-open').checked=Boolean(t.registration_open);notice('tournamentSaveStatus','Editing '+t.title);loadTournamentEntries();$('tournamentEditor').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadTournamentEntries(){
  const el=$('tournamentEntries');if(!tournamentId){el.textContent='Save or select a tournament first.';return}if(!tournamentAdminData.canCheckIn){el.textContent='Your role does not have access to player contact details or check-in.';return}
  el.textContent='Loading players…';const selectedId=tournamentId;
  try{const d=await api('tournament-entries?id='+encodeURIComponent(selectedId));if(selectedId!==tournamentId)return;
    el.innerHTML='<p class="tournament-admin-counts">'+d.entries.length+' registered · '+d.entries.filter(e=>e.checked_in).length+' checked in</p>'+(d.entries.length?'<div class="tournament-table-wrap"><table><thead><tr><th>Player</th><th>Contact</th><th>Rating</th><th>Check-in</th></tr></thead><tbody>'+d.entries.map(e=>'<tr><td>'+esc(e.name)+'</td><td>'+esc(e.email)+(e.phone?'<small>'+esc(e.phone)+'</small>':'')+'</td><td>'+(e.rating??'Unrated')+'</td><td><button class="secondary" data-checkin="'+esc(e.id)+'" data-checked="'+Boolean(e.checked_in)+'">'+(e.checked_in?'Undo check-in':'Check in')+'</button></td></tr>').join('')+'</tbody></table></div>':'<p>No players registered yet.</p>');
    el.querySelectorAll('[data-checkin]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('tournament-checkin',{id:button.dataset.checkin,tournamentId:selectedId,checkedIn:button.dataset.checked!=='true'});await loadTournamentEntries()}catch(e){notice('tournamentSaveStatus',e.message,true);button.disabled=false}});
  }catch(e){el.textContent=e.message}
}
$('newTournament').onclick=newTournament;$('refreshTournamentEntries').onclick=loadTournamentEntries;
$('tournamentForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const result=await api('tournament',{id:tournamentId,title:$('t-title').value,venue:$('t-venue').value,start:$('t-start').value,capacity:$('t-capacity').value,published:$('t-published').checked,registrationOpen:$('t-open').checked,details:{photos:tournamentPhotos,...Object.fromEntries(['checkIn','fee','format','timeControl','rounds','map','pairings','results','eligibility','rules','prizes','winner','runnerUp','thirdPlace','news'].map(k=>[k,$('t-'+k).value]))}});tournamentId=result.id;notice('tournamentSaveStatus',result.message);await loadTournaments();await loadTournamentEntries()}catch(err){notice('tournamentSaveStatus',err.message,true)}finally{button.disabled=false}};
