let tournamentId=null,tournamentAdminData={tournaments:[],canEdit:false,canCheckIn:false};
const localTournamentTime=v=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)).replace(' ','T'):'';
const tournamentInput=(id,label,type='text',required=false,max='')=>'<div><label for="t-'+id+'">'+label+'</label><input id="t-'+id+'" name="'+id+'" type="'+type+'" '+(required?'required ':'')+(max?'maxlength="'+max+'"':'')+'></div>';
const tournamentArea=document.createElement('section');tournamentArea.id='tournamentArea';tournamentArea.className='admin-layout hidden';
tournamentArea.innerHTML='<aside class="panel saved"><div class="section-head"><h2>Tournaments</h2><button class="secondary" id="newTournament">New tournament</button></div><div id="savedTournaments" role="status"></div></aside><div><section class="panel" id="tournamentEditor"><h2>Tournament editor</h2><p>Dates and times use Malaysia time. Drafts are only visible to the team.</p><form id="tournamentForm"><fieldset id="tournamentFields" style="border:0;padding:0;margin:0;min-width:0"><div class="tournament-admin-fields">'+tournamentInput('title','Tournament name','text',true,120)+tournamentInput('venue','Venue & address','text',true,200)+tournamentInput('start','First round','datetime-local',true)+tournamentInput('checkIn','Check-in opens','datetime-local')+tournamentInput('fee','Entry fee (e.g. RM 25 or Free)','text',true,120)+tournamentInput('capacity','Maximum players','number',true)+tournamentInput('format','Format (e.g. Swiss)','text',true,120)+tournamentInput('timeControl','Time control (e.g. 10+5)','text',true,120)+tournamentInput('rounds','Number of rounds','number',true)+tournamentInput('map','Venue map link','url',false,2000)+tournamentInput('pairings','Pairings & standings link','url',false,2000)+tournamentInput('results','Final results link','url',false,2000)+'<div class="wide"><label for="t-eligibility">Eligibility</label><textarea id="t-eligibility" maxlength="500" placeholder="Age groups, rating limits, or open to all"></textarea><label for="t-rules">Rules & arrival information</label><textarea id="t-rules" maxlength="5000"></textarea><label for="t-prizes">Prizes (optional)</label><textarea id="t-prizes" maxlength="1000"></textarea></div></div><label class="check"><input id="t-published" type="checkbox"> Publish tournament</label><label class="check"><input id="t-open" type="checkbox"> Accept registrations until the first round or capacity is reached</label><button class="primary" type="submit">Save tournament</button></fieldset><p id="tournamentSaveStatus" role="status"></p></form></section><section class="panel" style="margin-top:24px"><div class="section-head"><h2>Players & check-in</h2><button id="refreshTournamentEntries" class="secondary">Refresh players</button></div><div id="tournamentEntries" role="status">Save or select a tournament to view its players.</div></section></div>';
$('admin-main').append(tournamentArea);
const tournamentTab=document.createElement('button');tournamentTab.id='tabTournaments';tournamentTab.className='secondary';tournamentTab.textContent='Tournaments';$('tabPosts').after(tournamentTab);
for(const id of ['tabPuzzles','tabPosts'])$(id).addEventListener('click',()=>{tournamentArea.classList.add('hidden');tournamentTab.classList.remove('primary')});
tournamentTab.onclick=()=>{for(const id of ['puzzleArea','postArea'])$(id).classList.add('hidden');for(const id of ['tabPuzzles','tabPosts'])$(id).classList.remove('primary');tournamentArea.classList.remove('hidden');tournamentTab.classList.add('primary');loadTournaments()};
$('t-capacity').min='1';$('t-capacity').max='1000';$('t-rounds').min='1';$('t-rounds').max='30';
async function loadTournaments(){
  $('savedTournaments').textContent='Loading…';
  try{tournamentAdminData=await api('tournaments');$('tournamentFields').disabled=!tournamentAdminData.canEdit;$('newTournament').disabled=!tournamentAdminData.canEdit;
    $('savedTournaments').innerHTML=tournamentAdminData.tournaments.length?tournamentAdminData.tournaments.map(t=>'<button class="saved-row" data-edit-tournament="'+esc(t.id)+'"><b>'+esc(t.title)+'</b><span>'+esc(localTournamentTime(t.start_at).replace('T',' '))+' MYT · '+(t.published?'Published':'Draft')+'</span><span>'+t.registered+' / '+t.capacity+' players</span></button>').join(''):'<p>No tournaments yet. Create a draft to get started.</p>';
    document.querySelectorAll('[data-edit-tournament]').forEach(b=>b.onclick=()=>editTournament(b.dataset.editTournament));
    if(!tournamentAdminData.canEdit)notice('tournamentSaveStatus','Your role has read-only access to tournament details.');
  }catch(e){$('savedTournaments').textContent=e.message}
}
function newTournament(){tournamentId=null;$('tournamentForm').reset();$('tournamentEntries').textContent='Save this tournament to manage registrations.';notice('tournamentSaveStatus','New draft.');$('t-title').focus()}
function editTournament(id){const t=tournamentAdminData.tournaments.find(t=>t.id===id);if(!t)return;tournamentId=id;for(const k of ['title','venue','capacity'])$('t-'+k).value=t[k];$('t-start').value=localTournamentTime(t.start_at);$('t-checkIn').value=localTournamentTime(t.details.checkIn);for(const k of ['fee','format','timeControl','rounds','map','pairings','results','eligibility','rules','prizes'])$('t-'+k).value=t.details[k]||'';$('t-published').checked=Boolean(t.published);$('t-open').checked=Boolean(t.registration_open);notice('tournamentSaveStatus','Editing '+t.title);loadTournamentEntries();$('tournamentEditor').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadTournamentEntries(){
  const el=$('tournamentEntries');if(!tournamentId){el.textContent='Save or select a tournament first.';return}if(!tournamentAdminData.canCheckIn){el.textContent='Your role does not have access to player contact details or check-in.';return}
  el.textContent='Loading players…';const selectedId=tournamentId;
  try{const d=await api('tournament-entries?id='+encodeURIComponent(selectedId));if(selectedId!==tournamentId)return;
    el.innerHTML='<p class="tournament-admin-counts">'+d.entries.length+' registered · '+d.entries.filter(e=>e.checked_in).length+' checked in</p>'+(d.entries.length?'<div class="tournament-table-wrap"><table><thead><tr><th>Player</th><th>Contact</th><th>Rating</th><th>Check-in</th></tr></thead><tbody>'+d.entries.map(e=>'<tr><td>'+esc(e.name)+'</td><td>'+esc(e.email)+(e.phone?'<small>'+esc(e.phone)+'</small>':'')+'</td><td>'+(e.rating??'Unrated')+'</td><td><button class="secondary" data-checkin="'+esc(e.id)+'" data-checked="'+Boolean(e.checked_in)+'">'+(e.checked_in?'Undo check-in':'Check in')+'</button></td></tr>').join('')+'</tbody></table></div>':'<p>No players registered yet.</p>');
    el.querySelectorAll('[data-checkin]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('tournament-checkin',{id:button.dataset.checkin,tournamentId:selectedId,checkedIn:button.dataset.checked!=='true'});await loadTournamentEntries()}catch(e){notice('tournamentSaveStatus',e.message,true);button.disabled=false}});
  }catch(e){el.textContent=e.message}
}
$('newTournament').onclick=newTournament;$('refreshTournamentEntries').onclick=loadTournamentEntries;
$('tournamentForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const result=await api('tournament',{id:tournamentId,title:$('t-title').value,venue:$('t-venue').value,start:$('t-start').value,capacity:$('t-capacity').value,published:$('t-published').checked,registrationOpen:$('t-open').checked,details:Object.fromEntries(['checkIn','fee','format','timeControl','rounds','map','pairings','results','eligibility','rules','prizes'].map(k=>[k,$('t-'+k).value]))});tournamentId=result.id;notice('tournamentSaveStatus',result.message);await loadTournaments();await loadTournamentEntries()}catch(err){notice('tournamentSaveStatus',err.message,true)}finally{button.disabled=false}};
